### PR TITLE
Add Ruby 2.4 support

### PR DESCRIPTION
**Pull request by tomasv**
https://github.com/mezis/blurrily/issues/46

I dug around and think found the issue.

`-Werror` makes all warning fatal during compilation, and for some reason unused argument warnings started appearing with Ruby 2.4.

The tests pass on my machine.

### CODE REVIEW

**Comment by tomasv** [comment]
Seems the Travis build failed only on 1.9.3, is that an issue?

```
NoMethodError: undefined method `spec' for nil:NilClass
```
during `bundle install`

**Comment by tomasv** [comment]
Fixed the failing build on 1.9.3 as well, the cause was an out of date bundler.

**Comment by tomasv** [comment]
@mezis

**Comment by tomasv** [comment]
I worked around this by using my own fork. @mezis feel free to reopen. :)
