### ISSUE TITLE
Ruby 2.2

### ISSUE THREAD

**Issue by amencarini** [mezis/blurrily#40]
Hey, I can't seem to be able to make Blurrily work on Ruby 2.2. Not sure if it's me being daft, Ruby C API changed or else.

```
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling map_ext.c
In file included from map_ext.c:3:
In file included from ./storage.h:10:
./blurrily.h:9:9: error: 'PACKED_STRUCT' macro redefined [-Werror]
#define PACKED_STRUCT __attribute__ ((__packed__))
        ^
/Users/ale/.rbenv/versions/2.2.0/include/ruby-2.2.0/x86_64-darwin14/ruby/config.h:66:9: note: previous definition is here
#define PACKED_STRUCT(x) x __attribute__((packed))
        ^
1 error generated.
make: *** [map_ext.o] Error 1

make failed, exit code 2
```

**Comment by mezis** [comment]
I'll take a look. It's likely Clang related, not Ruby 2.2 related; hopefully just a missing `#ifndef`.

**Comment by mezis** [comment]
Just pushed v1.0.2, green under Ruby 2.2. Thanks for the heads up @amencarini!
